### ISSUE TITLE
WebUI: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#518]
**Describe the bug**

After upgrading to 2.2.0, I am trying the web interface at `http://x.x.x.x:3080/static/web-ui/server/1/project/<uuid>`

I find that all the icons are displayed for devices, but no lines are shown between them.

In addition, a message pops up saying "Cannot read property 'forEach' of undefined" when the page is first refreshed, or when clicking the "+" icon to zoom the topology, or when stretching the browser window.  I suspect this is related to the lack of lines.

**GNS3 version and operating system (please complete the following information):**
 - OS: gns3-gui macOS 10.14.6; browser Chrome 77.0.3865.90; gns3-server backend Ubuntu 18.04.3 amd64
 - GNS3 version: 2.2.0
 - remote server on bare metal

**To Reproduce**
1. Start server
2. Load topology
3. In GUI, select `Tools > Light Web Interface`.  Takes you to browser.
4. In browser, click on "WebUI - bundled" then select the topology.

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/44789/66044324-2e957280-e519-11e9-9bec-9c010e39df58.png)

**Additional context**
Backtrace from developer console (Chrome)

```
TypeError: Cannot read property 'forEach' of undefined
    at r.<anonymous> (main.9b1bd2eea6a0063aafe5.js:1)
    at r.O36p.r.forEach.r.each (main.9b1bd2eea6a0063aafe5.js:1)
    at n.fixStyles (main.9b1bd2eea6a0063aafe5.js:1)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at Array.map (<anonymous>)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at Array.map (<anonymous>)
    at n.setLinks (main.9b1bd2eea6a0063aafe5.js:1)
    at n.redraw (main.9b1bd2eea6a0063aafe5.js:1)
    at n.changeLayout (main.9b1bd2eea6a0063aafe5.js:1)
    at n.ngOnChanges (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at main.9b1bd2eea6a0063aafe5.js:1
    at CC (main.9b1bd2eea6a0063aafe5.js:1)
    at GC (main.9b1bd2eea6a0063aafe5.js:1)
    at Object.updateDirectives (main.9b1bd2eea6a0063aafe5.js:1)
    at Object.updateDirectives (main.9b1bd2eea6a0063aafe5.js:1)
    at yC (main.9b1bd2eea6a0063aafe5.js:1)
    at IC (main.9b1bd2eea6a0063aafe5.js:1)
    at TC (main.9b1bd2eea6a0063aafe5.js:1)
    at yC (main.9b1bd2eea6a0063aafe5.js:1)
    at IC (main.9b1bd2eea6a0063aafe5.js:1)
    at TC (main.9b1bd2eea6a0063aafe5.js:1)
    at yC (main.9b1bd2eea6a0063aafe5.js:1)
    at IC (main.9b1bd2eea6a0063aafe5.js:1)
    at RC (main.9b1bd2eea6a0063aafe5.js:1)
    at yC (main.9b1bd2eea6a0063aafe5.js:1)
    at IC (main.9b1bd2eea6a0063aafe5.js:1)
    at TC (main.9b1bd2eea6a0063aafe5.js:1)
    at yC (main.9b1bd2eea6a0063aafe5.js:1)
    at IC (main.9b1bd2eea6a0063aafe5.js:1)
    at RC (main.9b1bd2eea6a0063aafe5.js:1)
    at Object.yC [as checkAndUpdateView] (main.9b1bd2eea6a0063aafe5.js:1)
    at n.detectChanges (main.9b1bd2eea6a0063aafe5.js:1)
    at n.tick (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at e.invoke (polyfills.ca9df831504175955169.js:1)
    at Object.onInvoke (main.9b1bd2eea6a0063aafe5.js:1)
    at e.invoke (polyfills.ca9df831504175955169.js:1)
    at t.run (polyfills.ca9df831504175955169.js:1)
    at n.run (main.9b1bd2eea6a0063aafe5.js:1)
    at Object.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.i [as _next] (main.9b1bd2eea6a0063aafe5.js:1)
    at e.__tryOrUnsub (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
n.<computed> @ main.9b1bd2eea6a0063aafe5.js:1
main.9b1bd2eea6a0063aafe5.js:1 TypeError: Cannot read property 'forEach' of undefined
    at r.<anonymous> (main.9b1bd2eea6a0063aafe5.js:1)
    at r.O36p.r.forEach.r.each (main.9b1bd2eea6a0063aafe5.js:1)
    at n.fixStyles (main.9b1bd2eea6a0063aafe5.js:1)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at Array.map (<anonymous>)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at Array.map (<anonymous>)
    at n.setLinks (main.9b1bd2eea6a0063aafe5.js:1)
    at n.redraw (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at e.i [as _next] (main.9b1bd2eea6a0063aafe5.js:1)
    at e.__tryOrUnsub (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.emit (main.9b1bd2eea6a0063aafe5.js:1)
    at n.detectChanges (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.__tryOrUnsub (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.n.set (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.__tryOrUnsub (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.notifyNext (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.notifyNext (main.9b1bd2eea6a0063aafe5.js:1)
    at e._next (main.9b1bd2eea6a0063aafe5.js:1)
    at e.next (main.9b1bd2eea6a0063aafe5.js:1)
    at XMLHttpRequest.s (main.9b1bd2eea6a0063aafe5.js:1)
    at XMLHttpRequest.o (main.9b1bd2eea6a0063aafe5.js:1)
    at e.invokeTask (polyfills.ca9df831504175955169.js:1)
    at Object.onInvokeTask (main.9b1bd2eea6a0063aafe5.js:1)
n.<computed> @ main.9b1bd2eea6a0063aafe5.js:1
2sentry.io/api/842726/store/?sentry_version=7&sentry_client=raven-js%2F3.27.2&sentry_key=b2b1cfd9b043491eb6b566fd8acee358:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
17f0653f-71d2-46e4-8521-28cb40d5927d:1 Access to XMLHttpRequest at 'https://sentry.io/api/842726/store/?sentry_version=7&sentry_client=raven-js%2F3.27.2&sentry_key=b2b1cfd9b043491eb6b566fd8acee358' from origin 'http://10.12.254.116:3080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.9b1bd2eea6a0063aafe5.js:1 TypeError: Cannot read property 'forEach' of undefined
    at r.<anonymous> (main.9b1bd2eea6a0063aafe5.js:1)
    at r.O36p.r.forEach.r.each (main.9b1bd2eea6a0063aafe5.js:1)
    at n.fixStyles (main.9b1bd2eea6a0063aafe5.js:1)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at Array.map (<anonymous>)
    at n.convert (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at Array.map (<anonymous>)
    at n.setLinks (main.9b1bd2eea6a0063aafe5.js:1)
    at n.redraw (main.9b1bd2eea6a0063aafe5.js:1)
    at n.changeLayout (main.9b1bd2eea6a0063aafe5.js:1)
    at n.onResize (main.9b1bd2eea6a0063aafe5.js:1)
    at Object.handleEvent (main.9b1bd2eea6a0063aafe5.js:1)
    at Object.handleEvent (main.9b1bd2eea6a0063aafe5.js:1)
    at Object.handleEvent (main.9b1bd2eea6a0063aafe5.js:1)
    at xh (main.9b1bd2eea6a0063aafe5.js:1)
    at main.9b1bd2eea6a0063aafe5.js:1
    at main.9b1bd2eea6a0063aafe5.js:1
    at o (main.9b1bd2eea6a0063aafe5.js:1)
    at e.invokeTask (polyfills.ca9df831504175955169.js:1)
    at Object.onInvokeTask (main.9b1bd2eea6a0063aafe5.js:1)
    at e.invokeTask (polyfills.ca9df831504175955169.js:1)
    at t.runTask (polyfills.ca9df831504175955169.js:1)
    at t.invokeTask [as invoke] (polyfills.ca9df831504175955169.js:1)
    at _ (polyfills.ca9df831504175955169.js:1)
    at m (polyfills.ca9df831504175955169.js:1)
n.<computed> @ main.9b1bd2eea6a0063aafe5.js:1
```

Note that it also attempts to post to sentry.io, but this is blocked by browser CORS policy (which I have not altered).

**Comment by piotrpekala7** [comment]
Does the problem also occur after refreshing the page?

**Comment by candlerb** [comment]
Yes.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/519

**Comment by candlerb** [comment]
Can this issue be reopened please? I still see what appears to be exactly the same issue with `gns3-server 2.2.9~bionic1` and the built-in web UI.  Specifically:

* message pops up "Cannot read property 'forEach' of undefined"
* topology does not display links between nodes

![image](https://user-images.githubusercontent.com/44789/83978292-4de16c80-a8fe-11ea-852d-2ef8a663a151.png)

Backtraces from web browser (Chrome):

```
main.0846ddc10f839bedfff3.js:1 TypeError: Cannot read property 'forEach' of undefined
    at r.<anonymous> (main.0846ddc10f839bedfff3.js:1)
    at r.O36p.r.forEach.r.each (main.0846ddc10f839bedfff3.js:1)
    at n.fixStyles (main.0846ddc10f839bedfff3.js:1)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at Array.map (<anonymous>)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at Array.map (<anonymous>)
    at n.setLinks (main.0846ddc10f839bedfff3.js:1)
    at n.redraw (main.0846ddc10f839bedfff3.js:1)
    at n.changeLayout (main.0846ddc10f839bedfff3.js:1)
    at n.ngOnChanges (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at main.0846ddc10f839bedfff3.js:1
    at Uy (main.0846ddc10f839bedfff3.js:1)
    at mC (main.0846ddc10f839bedfff3.js:1)
    at Object.updateDirectives (main.0846ddc10f839bedfff3.js:1)
    at Object.updateDirectives (main.0846ddc10f839bedfff3.js:1)
    at Hy (main.0846ddc10f839bedfff3.js:1)
    at $y (main.0846ddc10f839bedfff3.js:1)
    at Yy (main.0846ddc10f839bedfff3.js:1)
    at Hy (main.0846ddc10f839bedfff3.js:1)
    at $y (main.0846ddc10f839bedfff3.js:1)
    at Yy (main.0846ddc10f839bedfff3.js:1)
    at Hy (main.0846ddc10f839bedfff3.js:1)
    at $y (main.0846ddc10f839bedfff3.js:1)
    at Xy (main.0846ddc10f839bedfff3.js:1)
    at Hy (main.0846ddc10f839bedfff3.js:1)
    at $y (main.0846ddc10f839bedfff3.js:1)
    at Yy (main.0846ddc10f839bedfff3.js:1)
    at Hy (main.0846ddc10f839bedfff3.js:1)
    at $y (main.0846ddc10f839bedfff3.js:1)
    at Xy (main.0846ddc10f839bedfff3.js:1)
    at Object.Hy [as checkAndUpdateView] (main.0846ddc10f839bedfff3.js:1)
    at n.detectChanges (main.0846ddc10f839bedfff3.js:1)
    at n.tick (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at e.invoke (polyfills.312ad1f991887572d9bc.js:1)
    at Object.onInvoke (main.0846ddc10f839bedfff3.js:1)
    at e.invoke (polyfills.312ad1f991887572d9bc.js:1)
    at t.run (polyfills.312ad1f991887572d9bc.js:1)
    at n.run (main.0846ddc10f839bedfff3.js:1)
    at Object.next (main.0846ddc10f839bedfff3.js:1)
    at e.i [as _next] (main.0846ddc10f839bedfff3.js:1)
    at e.__tryOrUnsub (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
n.<computed> @ main.0846ddc10f839bedfff3.js:1

main.0846ddc10f839bedfff3.js:1 TypeError: Cannot read property 'forEach' of undefined
    at r.<anonymous> (main.0846ddc10f839bedfff3.js:1)
    at r.O36p.r.forEach.r.each (main.0846ddc10f839bedfff3.js:1)
    at n.fixStyles (main.0846ddc10f839bedfff3.js:1)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at Array.map (<anonymous>)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at Array.map (<anonymous>)
    at n.setLinks (main.0846ddc10f839bedfff3.js:1)
    at n.redraw (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at e.i [as _next] (main.0846ddc10f839bedfff3.js:1)
    at e.__tryOrUnsub (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e.emit (main.0846ddc10f839bedfff3.js:1)
    at n.detectChanges (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.__tryOrUnsub (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e.n.set (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.__tryOrUnsub (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e.notifyNext (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at e.notifyNext (main.0846ddc10f839bedfff3.js:1)
    at e._next (main.0846ddc10f839bedfff3.js:1)
    at e.next (main.0846ddc10f839bedfff3.js:1)
    at XMLHttpRequest.s (main.0846ddc10f839bedfff3.js:1)
    at XMLHttpRequest.o (main.0846ddc10f839bedfff3.js:1)
    at e.invokeTask (polyfills.312ad1f991887572d9bc.js:1)
    at Object.onInvokeTask (main.0846ddc10f839bedfff3.js:1)
n.<computed> @ main.0846ddc10f839bedfff3.js:1

main.0846ddc10f839bedfff3.js:1 TypeError: Cannot read property 'forEach' of undefined
    at r.<anonymous> (main.0846ddc10f839bedfff3.js:1)
    at r.O36p.r.forEach.r.each (main.0846ddc10f839bedfff3.js:1)
    at n.fixStyles (main.0846ddc10f839bedfff3.js:1)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at Array.map (<anonymous>)
    at n.convert (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at Array.map (<anonymous>)
    at n.setLinks (main.0846ddc10f839bedfff3.js:1)
    at n.redraw (main.0846ddc10f839bedfff3.js:1)
    at n.changeLayout (main.0846ddc10f839bedfff3.js:1)
    at n.onResize (main.0846ddc10f839bedfff3.js:1)
    at Object.handleEvent (main.0846ddc10f839bedfff3.js:1)
    at Object.handleEvent (main.0846ddc10f839bedfff3.js:1)
    at Object.handleEvent (main.0846ddc10f839bedfff3.js:1)
    at Kf (main.0846ddc10f839bedfff3.js:1)
    at main.0846ddc10f839bedfff3.js:1
    at main.0846ddc10f839bedfff3.js:1
    at o (main.0846ddc10f839bedfff3.js:1)
    at e.invokeTask (polyfills.312ad1f991887572d9bc.js:1)
    at Object.onInvokeTask (main.0846ddc10f839bedfff3.js:1)
    at e.invokeTask (polyfills.312ad1f991887572d9bc.js:1)
    at t.runTask (polyfills.312ad1f991887572d9bc.js:1)
    at t.invokeTask [as invoke] (polyfills.312ad1f991887572d9bc.js:1)
    at _ (polyfills.312ad1f991887572d9bc.js:1)
    at m (polyfills.312ad1f991887572d9bc.js:1)
n.<computed> @ main.0846ddc10f839bedfff3.js:1
```

**Comment by piotrpekala7** [comment]
I don't know where the problem is, I can't reproduce it

**Comment by grossmj** [comment]
Maybe this happens when having a lot of nodes/links? I will try to create a project that can reproduce the problem.

**Comment by candlerb** [comment]
Can I share this project with you privately?

**Comment by grossmj** [comment]
> Can I share this project with you privately?

Yes, please. I will see if I can reproduce on my side.

**Comment by candlerb** [comment]
Done.  My browser is Chrome 83.0.4103.97 under macOS 10.14.6

Under Firefox I get "n.value.children is undefined" as the pop-up error.

**Comment by grossmj** [comment]
Thanks @candlerb. I am able to reproduce the error :+1:

**Comment by piotrpekala7** [comment]
probably it refers to https://sentry.io/organizations/gns3/issues/1715083680/?project=842726

**Comment by grossmj** [comment]
@piotrpekala7 yep looks like it. I am gonna share the project with you, including images so you can test on your side.

**Comment by piotrpekala7** [comment]
1) when it comes to links visibility, I have no clue how 'Cannot read property 'forEach' of undefined' error could appear, we check it here: https://github.com/GNS3/gns3-web-ui/blob/master/src/app/cartography/managers/graph-data-manager.ts#L47

**Comment by piotrpekala7** [comment]
> Under Firefox I get "n.value.children is undefined" as the pop-up error.

  -> should be fixed in https://github.com/GNS3/gns3-web-ui/commit/eb9102769c500db676017e3b2c5c98870eb88ffb

**Comment by piotrpekala7** [comment]
I check if value & value.children is defined

**Comment by candlerb** [comment]
Thank you!

As far as I can tell, that is compiled into `/usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/static/web-ui/main.0846ddc10f839bedfff3.js.map` - can you provide me with a rebuilt version of that file that I could test?

**Comment by grossmj** [comment]
> -> should be fixed in eb91027

I tested on my side and looks like the bug has been fixed. How can we let @candlerb test?

![Screenshot from 2020-06-08 21-02-00](https://user-images.githubusercontent.com/4752614/84025832-610e3e00-a9cb-11ea-9d2f-858cdee683aa.png)

**Comment by candlerb** [comment]
If you're happy with it then I can wait for 2.2.10.  Thanks again guys.

**Comment by piotrpekala7** [comment]
![linksIssue](https://user-images.githubusercontent.com/31202938/84031527-21792f00-a996-11ea-9bbe-dc660191cae9.PNG)

I tested on FF & chrome, looks fine

**Comment by grossmj** [comment]
Perfect, thanks for the fix @piotrpekala7
