### ISSUE TITLE
Issues when uploading images

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#847]
I have noticed issues when creating new templates and uploading images.

**When creating a new IOS router template**

I can upload IOS image (I see a confirmation message) however nothing appears in the drop down list.

![Screenshot from 2020-05-11 20-40-23](https://user-images.githubusercontent.com/4752614/81555518-df28f600-93c7-11ea-94a6-a8686aa94c63.png)

I can see the IOS image in has been uploaded on the GNS3 VM in `/opt/gns3/images/IOS`

```
gns3@gns3vm:/opt/gns3/images/IOS$ ls -l
total 91400
-rwx------ 1 gns3 gns3 93586267 May 11 11:36 c7200-adventerprisek9-mz.152-4.S6.image
-rw-r--r-- 1 gns3 gns3       32 May 11 11:36 c7200-adventerprisek9-mz.152-4.S6.image.md5sum
```

However, nothing is returned by using curl `http://172.16.9.132/v2/compute/dynamips/images`. This is because the uploaded image somehow got corrupted and is not a valid IOS image anymore. Therefore it cannot be listed by the server, most likely filtered out there: https://github.com/GNS3/gns3-server/blob/master/gns3server/utils/images.py#L72L78 and that why the drop down list is empty.

Using the desktop Ui to create a new template and uploading a new IOS image, I can see the IOS image size is different and that this time curl `http://172.16.9.132/v2/compute/dynamips/images` returns the images information.

```
gns3@gns3vm:/opt/gns3/images/IOS$ ls -l
total 91400
-rwx------ 1 gns3 gns3 93586040 May 11 11:35 c7200-adventerprisek9-mz.152-4.S6.image
-rw-r--r-- 1 gns3 gns3       32 May 11 11:35 c7200-adventerprisek9-mz.152-4.S6.image.md5sum
```

```
$ curl "http://172.16.9.132/v2/compute/dynamips/images"
[
    {
        "filename": "c7200-adventerprisek9-mz.152-4.S6.image",
        "filesize": 93586040,
        "md5sum": "8d0bbd5473b58ef5bbc7e926f56e174a",
        "path": "c7200-adventerprisek9-mz.152-4.S6.image"
    }
]
```

Also, I can select the image in the web-ui.

![Screenshot from 2020-05-11 21-22-31](https://user-images.githubusercontent.com/4752614/81558874-97a56880-93cd-11ea-8b8d-38c0ecad8586.png)

Maybe the web-ui reads images in text mode instead of binary to upload them to the server?

**When creating a new IOU device template**

It seems I cannot upload or list any images. Looks like no API calls are made to the server.

![Screenshot from 2020-05-11 20-54-36](https://user-images.githubusercontent.com/4752614/81559326-58c3e280-93ce-11ea-96ee-4f344bb362dc.png)

**When creating a new Qemu VM template**

Same as above, no Qemu image is uploaded.

![Screenshot from 2020-05-11 21-36-24](https://user-images.githubusercontent.com/4752614/81559921-8198a780-93cf-11ea-8ecc-f37e2fc73e42.png)

I can still create the template but the server complains that the image does not exist when I try to use it.

![Screenshot from 2020-05-11 21-33-14](https://user-images.githubusercontent.com/4752614/81559807-41d1c000-93cf-11ea-9d06-383012763661.png)

**When creating a new Docker container template**

I can add a new template with for instance the image "ubuntu:focal" and use it however I cannot see any existing Docker images.

![Screenshot from 2020-05-11 21-42-01](https://user-images.githubusercontent.com/4752614/81560414-83af3600-93d0-11ea-8505-c3652e36250b.png)

```
$ curl "http://172.16.9.132/v2/compute/docker/images"
[
    {
        "image": "ubuntu:focal"
    }
]
```

**Comment by piotrpekala7** [comment]
1 - IOS templates:
we're using application/octet-stream in uploader

url: "http://127.0.0.1:3080/v2/compute/dynamips/images/c3640-a3js-mz.124-25d.bin"
headers: []
withCredentials: false
formData: []
isReady: false
isUploading: false
isUploaded: true
isSuccess: true
isCancel: false
isError: false
progress: 100
index: undefined
uploader: FileUploader {isUploading: false, queue: Array(1), progress: 100, _nextIndex: 1, options: {…}, …}
some: File {name: "c3640-a3js-mz.124-25d.bin", lastModified: 1589202157448, lastModifiedDate: Mon May 11 2020 15:02:37 GMT+0200 (Central European Summer Time), webkitRelativePath: "", size: 32586744, …}
options: {autoUpload: false, isHTML5: true, filters: Array(1), removeAfterUpload: false, disableMultipart: false, …}
file: FileLikeObject {rawFile: File, size: 32586744, type: "application/octet-stream", name: "c3640-a3js-mz.124-25d.bin"}
_file: File {name: "c3640-a3js-mz.124-25d.bin", lastModified: 1589202157448, lastModifiedDate: Mon May 11 2020 15:02:37 GMT+0200 (Central European Summer Time), webkitRelativePath: "", size: 32586744, …}
method: "POST"
alias: "file"

unfortunately I don't see a problem on the web application side @ziajka could you confirm?

**Comment by piotrpekala7** [comment]
2,3 - IOU & QEMU templates:
we don't support uploading images - if you want to create a template you have to enter the full filepath

**Comment by grossmj** [comment]
> Yes, this is strange. I tried again today and this time using md5sum to compare the results:

The file on my computer:

```
$ md5sum c7200-adventerprisek9-mz.153-3.XB12.bin 
5d807ae4e9d177820d77456297c8bc5f  c7200-adventerprisek9-mz.153-3.XB12.bin
```

Then after it was uploaded to the GNS3 VM using the web-ui:

```
$ md5sum c7200-adventerprisek9-mz.153-3.XB12.bin
1b16a9e7bc44399921f13f055a21f4cc  c7200-adventerprisek9-mz.153-3.XB12.bin
```

Checksums are different... :(

> 2,3 - IOU & QEMU templates:
we don't support uploading images - if you want to create a template you have to enter the full filepath

Well, this is not user friendly nor consistent with IOS templates. We must support uploading images.

**Comment by grossmj** [comment]
The checksum is correct in the GNS3 VM if I upload using curl (for instance):

```
curl -X POST -H "Content-Type:application/octet-stream" "http://172.16.9.132/v2/compute/dynamips/images/c7200-adventerprisek9-mz.153-3.XB12.bin" --data-binary "@c7200-adventerprisek9-mz.153-3.XB12.bin"
```

**Comment by grossmj** [comment]
Just an idea, maybe you can try to set `disableMultipart` to `true` for `FileUploader`?https://github.com/valor-software/ng2-file-upload#properties-1

**Comment by ziajka** [comment]
Indeed disableMultipart may help.

**Comment by ziajka** [comment]
Stretch: E2E test

**Comment by piotrpekala7** [comment]
Is this endpoint valid https://gns3-server.readthedocs.io/en/latest/api/v2/compute/iou/iouimages.html?

**Comment by grossmj** [comment]
> Is this endpoint valid https://gns3-server.readthedocs.io/en/latest/api/v2/compute/iou/iouimages.html?

Yes, this should work:

```
curl "http://172.16.9.132/v2/compute/iou/images"
[
    {
        "filename": "i86bi-linux-l2-ipbasek9-15.1b.bin",
        "filesize": 64332184,
        "md5sum": "667c0608fff8a6db353ecbc88fa9c632",
        "path": "i86bi-linux-l2-ipbasek9-15.1b.bin"
    },
    {
        "filename": "i86bi-linux-l2-adventerprisek9-15.2d.bin",
        "filesize": 105036380,
        "md5sum": "f16db44433beb3e8c828db5ddad1de8a",
        "path": "i86bi-linux-l2-adventerprisek9-15.2d.bin"
    }
]
```

**Comment by piotrpekala7** [comment]
1 IOS router templates - tested & verified

**Comment by piotrpekala7** [comment]
3 Qemu vm templates - tested & verified

**Comment by grossmj** [comment]
IOS, IOU and Qemu images can successfully uploaded now. Thanks :+1: 

Out of curiosity, why IOS images were incorrectly uploaded?

**Comment by piotrpekala7** [comment]
@grossmj I fixed the error with IOS by changing the flag as you suggested. If listing docker images works correctly you can close this task, please let me know. I will create separate task with list of functionalities which should be covered in e2e tests, creating templates will be one of them

**Comment by grossmj** [comment]
> I fixed the error with IOS by changing the flag as you suggested.

Great, my intuition was right ;) I hope you did the same for other images (IOU & Qemu).

>  If listing docker images works correctly you can close this task, please let me know

This there is still a problem with Docker images.

I have created 2 Docker containers with the following images:

```
curl http://172.16.9.132/v2/compute/docker/images
[
    {
        "image": "ubuntu:bionic"
    },
    {
        "image": "ubuntu:focal"
    }
]
```
However, when I go in the preferences, I see 2 empty entries for existing images:

![Screenshot from 2020-05-15 20-53-33](https://user-images.githubusercontent.com/4752614/82045520-60e19200-96ee-11ea-81cd-44b4ce3187ea.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/6fc059bd1034a404001bd2056c0c3b3e587bd98a,

**Comment by piotrpekala7** [comment]
I'm sorry, I had a typo there

**Comment by grossmj** [comment]
I confirm this is fixed. I noticed some problems with Dynamips templates. I will create a new issue for these.
