### ISSUE TITLE
API requests doesn't use HTTPS when SSL is configured

### ISSUE THREAD

**Issue by Zmegolaz** [GNS3/gns3-web-ui#982]
Setting `ssl = true` in the gns3server settings enables HTTPS for the site, but the URLs for API requests (for example getting the list of projects) still reference `http://`, which means they get blocked by the browser.

**Comment by piotrpekala7** [comment]
@grossmj How will I know that SSL is configured?

**Comment by grossmj** [comment]
I think this should be explicitly chosen by users when they add the server information into the web-ui:

![Screenshot from 2020-09-12 02-22-46](https://user-images.githubusercontent.com/4752614/92952309-e6a7fb00-f49e-11ea-9c13-738cbd72a540.png)

Otherwise, one way to know is by looking at the local compute and check if the `protocol` field is `https`.

```
curl "http://127.0.0.1:3080/v2/computes"
[
    {
        "capabilities": {
            "node_types": [
                "cloud",
                "ethernet_hub",
                "ethernet_switch",
                "nat",
                "vpcs",
                "virtualbox",
                "dynamips",
                "frame_relay_switch",
                "atm_switch",
                "qemu",
                "vmware",
                "traceng",
                "docker",
                "iou"
            ],
            "platform": "linux",
            "version": "2.2.14dev1-90ecefd45"
        },
        "compute_id": "local",
        "connected": true,
        "cpu_usage_percent": 6.5,
        "host": "localhost",
        "last_error": null,
        "memory_usage_percent": 51.7,
        "name": "Server",
        "port": 3080,
        "protocol": "http",
        "user": "admin"
    }
]
```

**Comment by piotrpekala7** [comment]
![conf](https://user-images.githubusercontent.com/31202938/93197406-e08a7680-f74b-11ea-92d5-59b9fc826208.PNG)

I changed conf file (like on the screenshot) and still after requesting server I received 'http' as protocol

**Comment by piotrpekala7** [comment]
I created separate branch https://github.com/GNS3/gns3-web-ui/tree/API-requests-doesn't-use-HTTPS-when-SSL-is-configured, the only change is to use 'https' in url if server has authorization in http-server.service

**Comment by Zmegolaz** [comment]
I'm not that into how GNS3 has named stuff, but I'd say authorization and SSL doesn't really have anything to do with each other, shouldn't HTTPS be based on the `ssl` setting instead?

**Comment by julazcano** [comment]
@piotrpekala7 - I would love to test your branch on my deployment which is behind an SSL Reverse Proxy.  How can I approach this?

**Comment by julazcano** [comment]
@piotrpekala7 - I loaded up your branch for testing on a fresh gns3vm of 2.2.14.  Struggled at first because it seems like the vm uses port 80 instead 3080 for the unified web-ui, but after running the remote-install script within the gns3-server git repo, I leveraged the 'update-bundled-web-ui.sh script - passing in the repo of your branch locally on the vm.  (this is of course after installing node & yarn & dependencies).

After restarting the gns3 service with the /etc/gns3/gns3_server.conf file set with SSL & authorization, here is a screenshot that shows that some API calls like /v2/projects are still being sent via regular old http, which will break if I place and SSL reverse proxy in front.  Let me know if you have any further ideas on this - would love to get this working.

**Comment by julazcano** [comment]
![Screen Shot 2020-10-06 at 2 29 14 PM](https://user-images.githubusercontent.com/32578400/95262066-57151400-07e0-11eb-9e98-f8c93f857e09.png)

**Comment by julazcano** [comment]
Ah bummer - no i lied that I had tested your branch.  I misread what the update-bundled-web-ui script was doing.  So i just manually cloned down your branch and ran the yarn install / yarn ng build commands - however it seems that it could not build it successfully :(

gns3@gns3vm:~/gns3-web-ui$ yarn ng build --source-map=false --configuration=production --base-href /static/web-ui/
yarn run v1.22.5
$ ng build --source-map=false --configuration=production --base-href /static/web-ui/
...
90% chunk assets processing
<--- Last few GCs --->

[13366:0x3da7580]   431694 ms: Mark-sweep 977.0 (999.9) -> 976.1 (999.6) MB, 2096.3 / 0.0 ms  (average mu = 0.121, current mu = 0.031) allocation failure scavenge might not succeed
[13366:0x3da7580]   434035 ms: Mark-sweep 978.0 (999.6) -> 977.1 (1000.1) MB, 2288.2 / 0.0 ms  (average mu = 0.071, current mu = 0.023) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13cf099]
    1: StubFrame [pc: 0x1438487]
Security context: 0x207cfe7008d1 <JSObject>
    2: /* anonymous */ [0x23f50286e329] [/home/gns3/gns3-web-ui/node_modules/acorn/dist/acorn.js:2696] [bytecode=0x2d94305014b1 offset=0](this=0x193264983c51 <Parser map = 0x7d40143ff49>,0x19326498ccc1 <Node map = 0x91aec272399>,0x0ba63fc806e9 <false>)
    3: /* anonymous */ [0x23f50286e2a9] [/home/gns3/gns3-web-ui/node_modules/ac...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa093f0 node::Abort() [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 2: 0xa097fc node::OnFatalError(char const*, char const*) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 3: 0xb8431e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 4: 0xb84699 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 5: 0xd31055  [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 6: 0xd316e6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 7: 0xd3df65 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 8: 0xd3ee15 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
 9: 0xd418cc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
10: 0xd0837b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
11: 0x1049fbe v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
12: 0x13cf099  [ng build --source-map=false --configuration=production --base-href /static/web-ui/]
Aborted
error Command failed with exit code 134.

**Comment by julazcano** [comment]
The other problem I'm having as well when I attempt to enable SSL is that the controller can no longer connect to itself - meaning that from the web-ui, there are no servers present in the server list.  When SSL=False, i can always see in the GNS3 server logs:

2020-10-06 21:40:45 INFO compute.py:360 Connecting to compute 'local'
2020-10-06 21:40:45 INFO web_log.py:233 127.0.0.1 [06/Oct/2020:21:40:45 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.6 aiohttp/3.6.2"
2020-10-06 21:40:45 INFO notification_handler.py:50 New client has connected to compute WebSocket
2020-10-06 21:40:45 INFO compute.py:430 Connected to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'


However when SSL=True, i see this:

2020-10-06 21:20:50 INFO run.py:224 Config file /etc/gns3/gns3_server.conf loaded
2020-10-06 21:20:50 INFO run.py:237 HTTP authentication is enabled with username 'gns3'
2020-10-06 21:20:50 INFO run.py:244 Running with Python 3.6.9 and has PID 12890
2020-10-06 21:20:50 INFO run.py:79 Current locale is en_US.UTF-8
2020-10-06 21:20:50 INFO web_server.py:192 SSL is enabled
2020-10-06 21:20:50 INFO web_server.py:307 Starting server on 0.0.0.0:3080
2020-10-06 21:20:50 INFO __init__.py:62 Load controller configuration file /home/gns3/.config/GNS3/2.2/gns3_controller.conf
2020-10-06 21:20:50 INFO __init__.py:66 Controller is starting
2020-10-06 21:20:51 INFO compute.py:63 Create compute local
2020-10-06 21:20:51 INFO compute.py:360 Connecting to compute 'local'
2020-10-06 21:20:51 WARNING compute.py:363 Cannot connect to compute 'local':

**Comment by piotrpekala7** [comment]
@julazcano 

1) when it comes to - **FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory** - you mentioned above, you can find solution here https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas

2) you don't have to use ng build to test your changes, you can just run ng serve and open 4200 in browser

**Comment by piotrpekala7** [comment]
> The other problem I'm having as well when I attempt to enable SSL is that the controller can no longer connect to itself - meaning that from the web-ui, there are no servers present in the server list. When SSL=False, i can always see in the GNS3 server logs:
> 
> 2020-10-06 21:40:45 INFO compute.py:360 Connecting to compute 'local'
> 2020-10-06 21:40:45 INFO web_log.py:233 127.0.0.1 [06/Oct/2020:21:40:45 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.6 aiohttp/3.6.2"
> 2020-10-06 21:40:45 INFO notification_handler.py:50 New client has connected to compute WebSocket
> 2020-10-06 21:40:45 INFO compute.py:430 Connected to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'
> 
> However when SSL=True, i see this:
> 
> 2020-10-06 21:20:50 INFO run.py:224 Config file /etc/gns3/gns3_server.conf loaded
> 2020-10-06 21:20:50 INFO run.py:237 HTTP authentication is enabled with username 'gns3'
> 2020-10-06 21:20:50 INFO run.py:244 Running with Python 3.6.9 and has PID 12890
> 2020-10-06 21:20:50 INFO run.py:79 Current locale is en_US.UTF-8
> 2020-10-06 21:20:50 INFO web_server.py:192 SSL is enabled
> 2020-10-06 21:20:50 INFO web_server.py:307 Starting server on 0.0.0.0:3080
> 2020-10-06 21:20:50 INFO **init**.py:62 Load controller configuration file /home/gns3/.config/GNS3/2.2/gns3_controller.conf
> 2020-10-06 21:20:50 INFO **init**.py:66 Controller is starting
> 2020-10-06 21:20:51 INFO compute.py:63 Create compute local
> 2020-10-06 21:20:51 INFO compute.py:360 Connecting to compute 'local'
> 2020-10-06 21:20:51 WARNING compute.py:363 Cannot connect to compute 'local':

I do not understand why this error could appear, please try again with the new version and if there is a problem open the task in the gns3-server repository

**Comment by julazcano** [comment]
> > The other problem I'm having as well when I attempt to enable SSL is that the controller can no longer connect to itself - meaning that from the web-ui, there are no servers present in the server list. When SSL=False, i can always see in the GNS3 server logs:
> > 2020-10-06 21:40:45 INFO compute.py:360 Connecting to compute 'local'
> > 2020-10-06 21:40:45 INFO web_log.py:233 127.0.0.1 [06/Oct/2020:21:40:45 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 552 "-" "Python/3.6 aiohttp/3.6.2"
> > 2020-10-06 21:40:45 INFO notification_handler.py:50 New client has connected to compute WebSocket
> > 2020-10-06 21:40:45 INFO compute.py:430 Connected to compute 'local' WebSocket 'http://127.0.0.1:3080/v2/compute/notifications/ws'
> > However when SSL=True, i see this:
> > 2020-10-06 21:20:50 INFO run.py:224 Config file /etc/gns3/gns3_server.conf loaded
> > 2020-10-06 21:20:50 INFO run.py:237 HTTP authentication is enabled with username 'gns3'
> > 2020-10-06 21:20:50 INFO run.py:244 Running with Python 3.6.9 and has PID 12890
> > 2020-10-06 21:20:50 INFO run.py:79 Current locale is en_US.UTF-8
> > 2020-10-06 21:20:50 INFO web_server.py:192 SSL is enabled
> > 2020-10-06 21:20:50 INFO web_server.py:307 Starting server on 0.0.0.0:3080
> > 2020-10-06 21:20:50 INFO **init**.py:62 Load controller configuration file /home/gns3/.config/GNS3/2.2/gns3_controller.conf
> > 2020-10-06 21:20:50 INFO **init**.py:66 Controller is starting
> > 2020-10-06 21:20:51 INFO compute.py:63 Create compute local
> > 2020-10-06 21:20:51 INFO compute.py:360 Connecting to compute 'local'
> > 2020-10-06 21:20:51 WARNING compute.py:363 Cannot connect to compute 'local':
> 
> I do not understand why this error could appear, please try again with the new version and if there is a problem open the task in the gns3-server repository

Understood - have created issue #1826 under the server server repo.  Thanks.

**Comment by julazcano** [comment]
> @julazcano
> 
>     1. when it comes to - **FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory** - you mentioned above, you can find solution here https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas
> 
>     2. you don't have to use ng build to test your changes, you can just run ng serve and open 4200 in browser

Thanks bud - so learned a bit more about yarn and node and its making more sense to me now.
Testing with just the ng serve --host 0.0.0.0 option is a bit difficult because i have to use HTTP://x.x.x.x:4200 to get to the page but all the API calls are immediately trying to use https:// and was causing issues.  So I decided to build and push to the static/web-ui directory for the GNS3VM.  

Seems like there is progress with your logic, however I'm still seeing an http call for "projects".  Any chance you can have a look at the logic for that uri?

Cheers,
Juan


![Screen Shot 2020-10-12 at 5 05 23 PM](https://user-images.githubusercontent.com/32578400/95800940-94304900-0cad-11eb-89f8-d2f1b330d3a8.png)

**Comment by piotrpekala7** [comment]
@julazcano I added two logs on this branch https://github.com/GNS3/gns3-web-ui/tree/API-requests-doesn't-use-HTTPS-when-SSL-is-configured, please could you check what you have in console (console tab in developer tools of browser)?

**Comment by julazcano** [comment]
> @julazcano I added two logs on this branch https://github.com/GNS3/gns3-web-ui/tree/API-requests-doesn't-use-HTTPS-when-SSL-is-configured, please could you check what you have in console (console tab in developer tools of browser)?

Ah ya - I was wondering how I can 100% verify that the gns3server is truly running the packaged build code from your branch or not.  Here are the logs I see.
![Screen Shot 2020-10-13 at 10 39 44 AM](https://user-images.githubusercontent.com/32578400/95896221-c17a0700-0d40-11eb-9c72-9748418a0a5c.png)

**Comment by julazcano** [comment]
> > @julazcano I added two logs on this branch https://github.com/GNS3/gns3-web-ui/tree/API-requests-doesn't-use-HTTPS-when-SSL-is-configured, please could you check what you have in console (console tab in developer tools of browser)?
> 
> Ah ya - I was wondering how I can 100% verify that the gns3server is truly running the packaged build code from your branch or not. Here are the logs I see.
> ![Screen Shot 2020-10-13 at 10 39 44 AM](https://user-images.githubusercontent.com/32578400/95896221-c17a0700-0d40-11eb-9c72-9748418a0a5c.png)

From doing a search for index.html within /usr/local/lib/python3.6 - here are the directories where index.html is present.  

/usr/local/lib/python3.6/dist-packages/gns3server/templates/index.html
/usr/local/lib/python3.6/dist-packages/gns3server/static/web-ui/index.html
/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/templates/index.html
/usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/static/web-ui/index.html

I loaded your branch code from within gns3-web-ui/dist (after the **yarn ng build --source-map=false --configuration=production --base-href /static/web-ui/**) into the --> /usr/local/lib/python3.6/dist-packages/gns3_server-2.2.15-py3.6.egg/gns3server/static/web-ui/ directory.  

Let me know if that sounds right to you from the GNS3VM perspective.

**Comment by piotrpekala7** [comment]
@julazcano 

When you visit the project website you should see url logs with https instead of http, I tested it and it happened. I understand we have a problem on the server side (which you opened) but I don't understand where the problem is in the behavior of the web interface. I checked the status of requests from the browser after the changes, in fact I have not downloaded projects, but there are no http queries

**Comment by piotrpekala7** [comment]
should be fixed in https://github.com/GNS3/gns3-web-ui/pull/1000

**Comment by julazcano** [comment]
@piotrpekala7 

I'm still seeing calls for /projects & /version that are hardcoded with http even though the server is fully configured for SSL.  Can you have another look?  I've tested with the code that fixes the backend SSL issues on the gns3server.

![Screen Shot 2020-10-27 at 10 34 46 AM](https://user-images.githubusercontent.com/32578400/97340009-7f70bb00-1840-11eb-86dc-2c065d32de47.png)

**Comment by grossmj** [comment]
@piotrpekala7 can you have a look at this? This is the same as https://github.com/GNS3/gns3-web-ui/issues/982 Thanks :+1:

**Comment by grossmj** [comment]
I wanted to test locally by running the GNS3 backend with SSL enabled and then use the web-ui to connect to it however there is no option to select HTTPS protocol:

![Screenshot from 2020-10-28 12-23-11](https://user-images.githubusercontent.com/4752614/97381200-7f43ee80-1918-11eb-8fd2-06e4a304e3c0.png)

**Comment by piotrpekala7** [comment]
@grossmj 

look here https://github.com/GNS3/gns3-web-ui/pull/1000/files#diff-d61cd1d1acb8f40b57116ba752faa2826d0670c34d7e60b35790f1da71a51ddfR180, if server authorization is set all requests started with https

**Comment by piotrpekala7** [comment]
I am confused because all requests go through this service (no hardcoded queries etc, no such possibility)

**Comment by julazcano** [comment]
> I am confused because all requests go through this service (no hardcoded queries etc, no such possibility)

Hey mate - not sure about the hierarchy of the logic, but if you glance at various .ts files, such as projects below, you'll find various methods that have hardcoded http: references.  Could this be why I'm experiencing my non-ssl calls?

![Screen Shot 2020-11-02 at 12 52 32 PM](https://user-images.githubusercontent.com/32578400/97918208-97e24900-1d0a-11eb-93be-027e89ab6108.png)

**Comment by piotrpekala7** [comment]
@julazcano 

No, this is not the reason but it shouldn't be present in repo so I opened task - if you're interested you can track it here: https://github.com/GNS3/gns3-web-ui/issues/1006. Anyway, I see on your screenshot query to /version endpoint https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/server.service.ts#L145, I wonder if it's sth with SeverDiscoveryComponent.

**Comment by piotrpekala7** [comment]
we decided to add protocol field to server

will be fixed in https://github.com/GNS3/gns3-web-ui/issues/1007

**Comment by julazcano** [comment]
> we decided to add protocol field to server
> 
> will be fixed in #1007

Hi team,
I just retested, and I'm noticing that although the API calls are properly using HTTPS/SSL, for some reason the /projects and /version is hardcoding port 80 to the call.

For Reference:
Screenshot 1 shows the hardcoded SSL call on port 80 for /projects.

![Screenshot 1](https://user-images.githubusercontent.com/32578400/98858046-d1a30600-2414-11eb-8cfa-d5c9c865413d.png)

Screenshot 2 shows the hardcoded SSL cal on port 80 for /version.

![Screeshot 2](https://user-images.githubusercontent.com/32578400/98858043-d10a6f80-2414-11eb-859d-0735125f4fe8.png)
